name: DP

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Клонируем репозиторий
        run: |
          git clone https://github.com/${{ github.repository }} repo
          cd repo
          echo "Репозиторий склонирован"

      - name: Создаём файл
        run: |
          cd repo
          echo "Этот файл создан в GitHub Actions" > test.txt

      - name: Конфигур
        run: |
          cd repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Добавляем и коммитим файл
        run: |
          cd repo
          git add test.txt
          git commit -m "Add test"

      - name: Пушим изменения
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd repo
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push origin HEAD:${{ github.event.pull_request.head.ref }}

      
